Implement check for protected file changes
Added a job to check for modifications to protected files before the build job.

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -7,6 +7,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+    needs: check-protected-files
 
     strategy:
       matrix:
@@ -25,3 +26,38 @@ jobs:
 
     - name: build and run tests
       run: mvn test
+      
+  check-protected-files:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check for forbidden file changes
+        run: |
+          if [[ "$GITHUB_ACTOR" != "trusted-user" ]]; then
+              exit 1
+            fi
+
+          PROTECTED_FILES=(
+          "pom.xml"
+          ".github/workflows/protected-files.yml"
+          ".github/workflows/test-cases.yaml"
+          )
+
+          CHANGED_FILES=$(git diff --name-only origin/main..HEAD)
+
+          echo "Changed files:"
+          echo "${CHANGED_FILES}"
+
+          for file in "${PROTECTED_FILES[@]}"; do
+            if echo "${CHANGED_FILES}" | grep -qx "${file}"; then
+              echo "Error: ${file} must not me modified."
+              exit 1
+            fi
+          done
+
+          echo "No protected files were modified!"
